<ul id="links-modules">
	<li><a href="#"><span class="users">Administración de Usuarios</span></a></li>
	<li><a href="#"><span class="armamento">Armamento y Equipamiento Policial</span></a></li>
	<li><a href="#"><span class="transmisiones">Informática y Transmisiones</span></a></li>
	<li><a href="#"><span class="automovilismo">Automovilismo</span></a></li>
	<li><a href="#"><span class="servicios">Servicios</span></a></li>
	<li><a href="#"><span class="instruccion">Instrucción</span></a></li>
</ul>