<div id="notes" style="width: 100%;height:600px;"></div>
<p>Crear: Click en el botón "A&ntilde;adir Nota".</p>
<p>Editar: Doble click en el texto de una nota. Una vez cambiado el texto hacer click en la madera, o click fuera de la nota</p>
<p>Redimensionar: Poner el raton en el border derecho, inferior o en la esquina inferior derecha, 
hacer click y mantenerlo hasta que se consiga el tamaño deseado.</p>
<p>Mover: Arrastrar la nota al lugar que se quiera manteniendo click izquierdo sobre la nota.</p>
<p>Eliminar: Click en la X arriba a la izquierda de la nota.</p>