<p><?php echo $this->searchText;?></p>
<div id="grid">
	<h2>Materiales</h2>
	<?php echo $this->grid_materiales;?>		
	<h2>Usuarios Activos</h2>
	<?php echo $this->grid_users_activo;?>		
	<h2>Categorias de Materiales</h2>
	<?php echo $this->grid_categorias_materiales;?>				
	<h2>Usuarios Inactivos</h2>
	<?php echo $this->grid_users_inactivo;?>	
	<!-- 
	<h2>Informaciones Verbales</h2>
	<?php echo $this->grid_verbal;?>		
	-->
</div>